services:
  app:
    # Use PHP 7.2 with Apache to serve the Drupal site
    image: tugboatqa/php:7.2-apache

    # Set this as the default service. This does a few things
    #   1. Clones the git repository into the service container
    #   2. Exposes port 80 to the Tugboat HTTP proxy
    #   3. Routes requests to the preview URL to this service
    default: true

    # Wait until the mysql service is done building
    depends: mysql

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Install opcache and enable mod-rewrite.
        - docker-php-ext-install opcache
        - a2enmod headers rewrite

        # Install drush 8.1.17
        - composer --no-ansi global require drush/drush:8.1.17
        - ln -sf ~/.composer/vendor/bin/drush /usr/local/bin/drush

        # Link the document root to the expected path. This example links
        # /docroot to the docroot
        - ln -snf "${TUGBOAT_ROOT}/docroot" "${DOCROOT}"

      # Commands that import files, databases,  or other assets. When an
      # existing preview is refreshed, the build workflow starts here,
      # skipping the init step, because the results of that step will
      # already be present.
      update:
        # We have no external assets to update for testing the distro.
        
      build:
        # Run the make command to prepare our custom build
        - drush make build-govcms.make ${TUGBOAT_ROOT}/docroot/
        - drush make --no-core drupal-org.make ${TUGBOAT_ROOT}/docroot/ -y
       
        # Prepare for install.
        - rm -rf "${TUGBOAT_ROOT}/docroot/sites/default/"
        - mkdir "${TUGBOAT_ROOT}/docroot/sites/default/"
        - mkdir -p "${TUGBOAT_ROOT}/docroot/sites/default/files"
        - chgrp -R www-data "${TUGBOAT_ROOT}/docroot/sites/default/files"
        - find "${TUGBOAT_ROOT}/docroot/sites/default/files" -type d -exec chmod 2775 {} \;
        - find "${TUGBOAT_ROOT}/docroot/sites/default/files" -type f -exec chmod 0664 {} \;
        - cp "${TUGBOAT_ROOT}/.tugboat/settings.php" "${TUGBOAT_ROOT}/docroot/sites/default/"
       
        # Install the site.
        - drush -r "${DOCROOT}" si -y govcms

  # What to call the service hosting MySQL. This name also acts as the
  # hostname to access the service by from the php service.
  mysql:
    # Use the latest available 5.x version of MySQL
    image: tugboatqa/mysql:5
